export const localimag = {
    left_arrow: require('./Icons/arrow_icon.png'),
    back: require('./Icons/back.png'),
    question: require('./Icons/question.png'),
    // question: require('./Icons/question.png'),
    shopping_cart: require('./Icons/shopping_cart.png'),
    down: require('./Icons/down.png'),
    notification: require('./Icons/notification.png'),
    location: require('./Icons/location.png'),
    arrow_right: require('./Icons/arrow-right.png'),
    search: require('./Icons/search.png'),
    trend: require('./Icons/trend.png'),
    download_images: require('./Icons/download.jpeg'),
    images_12: require('./Icons/images_12.jpeg'),
    images: require('./Icons/images.jpeg'),
    man_image: require('./Icons/man_image.jpeg'),
    girl_withMobile: require('./Icons/girl_withMobile.jpeg'),
    black_mobile: require('./Icons/black_mobile.jpeg'),
    blanck_spaceMobile: require('./Icons/blanck_spaceMobile.jpeg'),
    electrician: require('./Icons/electrician.jpeg'),
    plumber_image: require('./Icons/plumber_image.jpeg'),
    ac_repair_image: require('./Icons/ac_repair_image.jpeg'),
    working_woman: require('./Icons/working_woman.jpeg'),
    carpentar_image: require('./Icons/carpentar_image.jpeg'),
    verius2: require('./Icons/verius2.jpeg'),
    coronaVerius: require('./Icons/coronaVerius.jpeg'),
    coronaVerius_image: require('./Icons/coronaVerius_image.jpeg'),

    ac_repair_image: require('./Icons/ac_repair_image.jpeg'),
    application: require('./Icons/application.jpeg'),
    bgBulb: require('./Icons/bgBulb.jpeg'),
    bulb: require('./Icons/bulb.jpeg'),
    manyBulbs: require('./Icons/manyBulbs.jpeg'),
    decorationBulb: require('./Icons/decorationBulb.jpeg'),
    newBulb: require('./Icons/newBulb.jpeg'),
    biring: require('./Icons/biring.jpeg'),
    biring1_image: require('./Icons/biring1_image.jpeg'),
    doorbell: require('./Icons/doorbell.jpeg'),
    doorbell_image: require('./Icons/doorbell_image.jpeg'),
    electrician1_image: require('./Icons/electrician1_image.jpeg'),
    genralElectrician: require('./Icons/genralElectrician.jpeg'),
    inveterImage: require('./Icons/inveterImage.jpeg'),
    inveters_images1: require('./Icons/inveters_images1.jpeg'),
    mcbfu_image: require('./Icons/mcbfu_image.jpeg'),
    mcbfuces: require('./Icons/mcbfuces.jpeg'),
    repairswitchboard: require('./Icons/repairswitchboard.jpeg'),
    switchbord: require('./Icons/switchbord.jpeg'),
    tvIntalletion: require('./Icons/tvIntalletion.jpeg'),
    // fan: require('./Icons/fan.jpeg'),
    fan1: require('./Icons/fan1.jpeg'),


}